"use strict";
exports.__esModule = true;
var ArrayList_1 = require("./ArrayList");
var arrayList = new ArrayList_1.ArrayList();
arrayList.add({ title: 'Lập trình JS' });
arrayList.add({ title: 'Lập trình PHP' });
arrayList.add({ title: 'Lập trình Java' });
console.log(arrayList.container);
arrayList.remove();
console.log(arrayList.container);
